apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wgxn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wgxn
    app.kubernetes.io/part-of: byoc-app-vceu
  name: wgxn
spec:
  rules:
  - host: wgxn-byoc-etqs-tenant.apps.50b1a5f5100d5863af67.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: wgxn
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
